### ISSUE TITLE
Berlin gtfs2gps function issues 

### ISSUE THREAD

**Issue by ahermanski** [ipeaGIT/gtfs2gps#77] opened 2019-12-25 21:19 UTC
I saw your package mentioned on twitter and wanted to try it out with the Berlin data available here : https://openmobilitydata.org/p/verkehrsverbund-berlin-brandenburg/213

To me it looked like the data was fine, sadly I wasn't able to make it work. There were two issues I found.

The first one leads to an empty file.

```r
berlin <- read_gtfs("gtfs.zip")

berlin_small_1 <- filter_by_shape_id(berlin, c(622))

berlin_gps_empty <- gtfs2gps(berlin_small_1, progress = TRUE, cores = 1, spatial_resolution = 15)
```
The second one brings up an error.
```r
berlin <- read_gtfs("gtfs.zip")

berlin_small_2 <- filter_by_shape_id(berlin, c(2655))

berlin_gps_error <- gtfs2gps(berlin_small_2, progress = TRUE, cores = 1, spatial_resolution = 15)


Fehler in head(newstop_t0, 1):(tail(newstop_t0, 1) - 1) : Argument der Länge 0

13.
update_dt(tripid, new_stoptimes, gtfs_data)
12.
FUN(X[[i]], ...)
11.
lapply(X = all_tripids, FUN = update_freq, new_stoptimes, gtfs_data)
10.
eval(lhs, parent, parent)
9.
eval(lhs, parent, parent)
8.
lapply(X = all_tripids, FUN = update_freq, new_stoptimes, gtfs_data) %>% data.table::rbindlist()
7.
FUN(X[[i]], ...)
6.
lapply(X[Split[[i]]], FUN, ...)
5.
pbapply::pblapply(X = all_shapeids, FUN = corefun)
4.
eval(lhs, parent, parent)
3.
eval(lhs, parent, parent)
2.
pbapply::pblapply(X = all_shapeids, FUN = corefun) %>% data.table::rbindlist()
1.
gtfs2gps(berlin_small_2, progress = TRUE, cores = 1, spatial_resolution = 15)
```

Even though to me, the gtfs looked more or less the same as the São Paulo one.

**Comment by rafapereirabr** [comment] 2019-12-26 16:08
Hi @ahermanski . There was a minor error in the `test_gtfs_freq.R` function. This fixed now and this should solve the 1st problem you reported. I'm looking into the 2nd problem to find the cause of the error.

**Comment by rafapereirabr** [comment] 2019-12-26 16:17
Apparently, all the `departure_time` values for the the `trip_id` _124193674_ are missing, which is causing the function to crash.

**Comment by ahermanski** [comment] 2019-12-26 16:46
So removing all `trip_id` with missing values should solve the issue?

**Comment by rafapereirabr** [comment] 2019-12-26 17:12
I've made a minor change to the function to ignore any `trip_id` with missing `departure_time` values. For now, the function will print a message of each problematic id to alert the user. Let me know if this is working now, @ahermanski .

**Comment by ahermanski** [comment] 2019-12-26 17:22
Yep, now it's working. Thank you for making those changes

**Comment by rafapereirabr** [comment] 2019-12-26 18:01
Thank you for helping us improve the package!

**Closed** 2020-01-07 00:42 UTC
