### ISSUE TITLE
arrival_time and departure_time in GPS data

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#139] opened 2020-07-29 18:19 UTC
Handle `arrival_time` and `departure_time` in GPS data. It currently uses only `departure_time`. Using `arrival_time` would create one additional point in the same place of the previous one with velocity and cumulative distance zero.

**Comment by rafapereirabr** [comment] 2021-12-15 17:57
duplicate of #197

**Closed** 2021-12-15 17:57 UTC
Labels: low priority
